//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDIM_Stock_Out
    {
        public string SO_ID { get; set; }
        public string SO_Me_ID { get; set; }
        public string SO_Me_Specification { get; set; }
        public Nullable<decimal> So_Me_Unit_Price { get; set; }
        public Nullable<decimal> SO_Me_Quantity { get; set; }
        public Nullable<System.DateTime> SO_Date { get; set; }
        public Nullable<int> SO_Flag { get; set; }
        public string SO_Audit_User_ID { get; set; }
        public string SO_Audit_User_Name { get; set; }
        public string SO_Audit_Advice { get; set; }
        public string SO_Remark { get; set; }
        public string SO_SI_ID { get; set; }
    }
}
