//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDIM_Inventory
    {
        public string Inv_ID { get; set; }
        public string Inv_Me_ID { get; set; }
        public string Inv_Me_Specification_ID { get; set; }
        public Nullable<decimal> Inv_Me_Unit_Price { get; set; }
        public Nullable<decimal> Inv_Me_Quantity { get; set; }
        public Nullable<System.DateTime> Inv_Date { get; set; }
        public string Inv_Remark { get; set; }
        public string Inv_SI_ID { get; set; }
        public Nullable<int> Inv_Flag { get; set; }
    }
}
