//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDIM_DataEntities : DbContext
    {
        public GDIM_DataEntities()
            : base("name=GDIM_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GDIM_Dict_Medicine> GDIM_Dict_Medicine { get; set; }
        public DbSet<GDIM_Dict_Medicine_Type> GDIM_Dict_Medicine_Type { get; set; }
        public DbSet<GDIM_Dict_Productor> GDIM_Dict_Productor { get; set; }
        public DbSet<GDIM_Dict_Specification> GDIM_Dict_Specification { get; set; }
        public DbSet<GDIM_Function> GDIM_Function { get; set; }
        public DbSet<GDIM_Function_Role> GDIM_Function_Role { get; set; }
        public DbSet<GDIM_Inventory> GDIM_Inventory { get; set; }
        public DbSet<GDIM_Role> GDIM_Role { get; set; }
        public DbSet<GDIM_Stock_In> GDIM_Stock_In { get; set; }
        public DbSet<GDIM_Stock_Out> GDIM_Stock_Out { get; set; }
        public DbSet<GDIM_User> GDIM_User { get; set; }
        public DbSet<GDIM_User_Role> GDIM_User_Role { get; set; }
    }
}
