//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDIM_User
    {
        public string User_ID { get; set; }
        public string User_Login_Name { get; set; }
        public string User_Pass_Word { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> User_Level { get; set; }
        public byte[] User_Image { get; set; }
    }
}
