//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDIM_Dict_Medicine
    {
        public string Me_ID { get; set; }
        public string Me_Trade_Name_E { get; set; }
        public string Me_Chemical_Name { get; set; }
        public string Me_Trade_Name_C { get; set; }
        public string Me_Specification_ID { get; set; }
        public Nullable<int> Me_Status { get; set; }
        public Nullable<decimal> Me_Unit_Price { get; set; }
        public string Me_Productor_ID { get; set; }
        public string Me_Type_ID { get; set; }
    }
}
